heat_template_version: 2018-08-31

description: infra

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      key_name: saubanov
      image: ubuntu-20.04
      flavor: m1.small
      networks:
        - port: { get_resource: server_port }
  
  server_port:
    type: OS::Neutron::Port
    properties:
      network_id: "17eae9b6-2168-4a07-a0d3-66d5ad2a9f0e"
  
  my_volume:
    type: OS::Cinder::Volume
    properties:
      size: 10
      name: my_volume_name
  
  volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: my_instance }
      volume_id: { get_resource: my_volume }
      mountpoint: /dev/vdb
  
